import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

window.CLINIC_DASHBOARD_READY = true;
const app = document.getElementById('app');
const config = window.CLINIC_SUPABASE || {};
const statusLabels = { new:'طلب جديد', contacted:'تم التواصل', confirmed:'موعد مؤكد', completed:'تمت الزيارة', no_show:'لم تحضر', cancelled:'أُلغي', rescheduled:'تم التأجيل' };
const statusIcons = { new:'fa-bell', contacted:'fa-phone-volume', confirmed:'fa-circle-check', completed:'fa-heart-circle-check', no_show:'fa-user-clock', cancelled:'fa-ban', rescheduled:'fa-clock-rotate-left' };
const staffRoles = new Set(['secretary', 'doctor']);
let supabase, session, profile, appointments = [], settings, activeView = 'home', selectedDate = new Date().toISOString().slice(0, 10);

function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char])); }
function safePhone(value = '') { return String(value).replace(/\D/g, ''); }
function safeAttachmentType(value = '') { return ['image/jpeg','image/png','image/webp','image/gif','application/pdf'].includes(value) ? value : 'application/octet-stream'; }
function attachmentData(a) { const base64 = String(a.attachment_base64 || '').replace(/[^A-Za-z0-9+/=]/g, ''); return base64 ? `data:${safeAttachmentType(a.attachment_type)};base64,${base64}` : ''; }
function typeText(type) { return { first:'كشف أول مرة', follow:'كشف متابعة', consult:'استشارة متابعة', aesthetic:'تجميل نسائي', birth:'حجز ولادة', labs:'تحاليل أو أشعة', contacts:'عائلة العيادة' }[type] || 'طلب من الموقع'; }
function formatDate(date, short = false) { return date ? new Date(`${date}T12:00:00`).toLocaleDateString('ar-EG', short ? { day:'numeric', month:'short' } : { weekday:'long', year:'numeric', month:'long', day:'numeric' }) : 'لم يُحدد موعد'; }
function requestDate(a) { return a.requested_date ? formatDate(a.requested_date) : (a.request_type === 'contacts' ? 'تسجيل بيانات للتواصل' : 'بانتظار تحديد موعد'); }
function wa(a) { const phone = safePhone(a.patients?.phone).replace(/^0/, '20'); const text = `مرحباً ${a.patients?.full_name || ''}، بخصوص ${typeText(a.request_type)}${a.requested_date ? ` بتاريخ ${a.requested_date}` : ''} في عيادة د. دعاء شعبان.`; return `https://wa.me/${phone}?text=${encodeURIComponent(text)}`; }
function pending(a) { return ['new', 'contacted', 'rescheduled'].includes(a.status); }
function hasAttachment(a) { return Boolean(attachmentData(a)); }
function appointmentById(id) { return appointments.find(a => a.id === Number(id)); }

if (!config.url || !config.anonKey) renderSetup(); else boot();

async function boot() {
  try {
    supabase = createClient(config.url, config.anonKey);
    ({ data: { session } } = await withTimeout(supabase.auth.getSession()));
    if (!session) return renderLogin();
    if (await withTimeout(loadData())) renderApp();
  } catch (error) {
    console.error(error);
    renderConnectionError();
  }
}

function renderSetup() { app.innerHTML = `<section class="login-page"><div class="login-card"><div class="clinic-mark"><i class="fa-solid fa-lock"></i></div><h1>لوحة إدارة العيادة</h1><p>أضيفي بيانات Supabase في ملف الإعدادات ثم أعيدي فتح الصفحة.</p></div></section>`; }
function renderConnectionError() { app.innerHTML = `<section class="login-page"><div class="login-card"><div class="clinic-mark"><i class="fa-solid fa-wifi"></i></div><h1>تعذر فتح لوحة الإدارة</h1><p>تأكدي من اتصال الإنترنت وأن ملف <b>js/config.js</b> ومجلد <b>dashboard</b> تم رفعهما كاملين إلى الاستضافة.</p><button class="primary-btn" type="button" onclick="location.reload()">إعادة المحاولة</button></div></section>`; }
function withTimeout(promise, milliseconds = 12000) { return Promise.race([promise, new Promise((_, reject) => setTimeout(() => reject(new Error('Connection timeout')), milliseconds))]); }
function renderLogin(error = '') {
  app.innerHTML = `<section class="login-page"><form class="login-card" id="loginForm"><div class="clinic-mark"><i class="fa-solid fa-heart-pulse"></i></div><h1>إدارة عيادة د. دعاء شعبان</h1><p>دخول السكرتارية والدكتورة فقط</p><label class="field">البريد الإلكتروني<input type="email" name="email" required autocomplete="username" placeholder="name@clinic.com"></label><label class="field">كلمة المرور<input type="password" name="password" required autocomplete="current-password" placeholder="••••••••"></label><div class="error">${escapeHtml(error)}</div><button class="primary-btn" type="submit">تسجيل الدخول <i class="fa-solid fa-arrow-left"></i></button></form></section>`;
  document.getElementById('loginForm').addEventListener('submit', login);
}
async function login(event) {
  event.preventDefault(); const form = new FormData(event.currentTarget);
  const { error } = await supabase.auth.signInWithPassword({ email: form.get('email'), password: form.get('password') });
  if (error) return renderLogin('بيانات الدخول غير صحيحة أو الحساب غير مفعّل.');
  ({ data: { session } } = await supabase.auth.getSession()); if (await loadData()) renderApp();
}
async function loadData() {
  const [profileRes, appointmentsRes, settingsRes] = await Promise.all([
    supabase.from('profiles').select('*').eq('id', session.user.id).single(),
    supabase.from('appointments').select('*, patients(id,full_name,phone), appointment_events(id,event_type,note,old_status,new_status,created_at)').order('created_at', { ascending:false }).limit(500),
    supabase.from('clinic_settings').select('*').eq('id', true).single()
  ]);
  profile = profileRes.data; appointments = appointmentsRes.data || []; settings = settingsRes.data;
  if (!profile || !staffRoles.has(profile.role)) { await supabase.auth.signOut(); session = null; renderLogin('هذا الحساب غير مخوّل لاستخدام لوحة الإدارة.'); return false; }
  return true;
}

function renderApp() {
  const staffName = escapeHtml(profile.full_name || session.user.email);
  app.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand"><i class="fa-solid fa-heart-pulse"></i><div><b>عيادة د. دعاء</b><span>لوحة متابعة الحجوزات</span></div></div><nav class="menu"><button data-view="home" class="${activeView === 'home' ? 'active' : ''}"><i class="fa-solid fa-house"></i><span>متابعة اليوم</span></button><button data-view="appointments" class="${activeView === 'appointments' ? 'active' : ''}"><i class="fa-solid fa-clipboard-list"></i><span>كل الطلبات</span></button><button data-view="patients" class="${activeView === 'patients' ? 'active' : ''}"><i class="fa-solid fa-users"></i><span>ملفات المريضات</span></button><button data-view="reports" class="${activeView === 'reports' ? 'active' : ''}"><i class="fa-solid fa-chart-pie"></i><span>ملخص الشهر</span></button>${profile.role === 'doctor' ? `<button data-view="settings" class="${activeView === 'settings' ? 'active' : ''}"><i class="fa-solid fa-gear"></i><span>إعدادات العيادة</span></button>` : ''}</nav><div class="side-bottom"><small>${staffName}</small><button class="ghost-btn" data-action="logout">تسجيل الخروج</button></div></aside><section class="workspace"><header class="topline"><div><h1>${viewTitle()}</h1><p>${new Date().toLocaleDateString('ar-EG',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</p></div><div class="user-chip"><i class="fa-solid fa-user-shield"></i><span>${staffName}</span><b>${profile.role === 'doctor' ? 'الدكتورة' : 'السكرتارية'}</b></div></header><div id="view"></div></section></div><div class="toast" id="toast" role="status"></div>`;
  renderView(); bindEvents();
}
function viewTitle() { return { home:'متابعة الحجوزات', appointments:'كل طلبات الحجز', patients:'ملفات المريضات', reports:'ملخص الشهر', settings:'إعدادات العيادة' }[activeView]; }
function renderView() { const view = document.getElementById('view'); view.innerHTML = activeView === 'home' ? homeView() : activeView === 'appointments' ? appointmentsView() : activeView === 'patients' ? patientsView() : activeView === 'reports' ? reportsView() : settingsView(); }
function stat(label, value, icon, tone = '') { return `<article class="stat ${tone}"><i class="fa-solid ${icon}"></i><span>${label}</span><b>${value}</b></article>`; }

function homeView() {
  const day = appointments.filter(a => a.requested_date === selectedDate);
  const followUp = appointments.filter(pending);
  const confirmed = day.filter(a => a.status === 'confirmed');
  const completed = day.filter(a => a.status === 'completed');
  return `<section class="quick-guide"><div><b><i class="fa-solid fa-circle-info"></i> طريقة العمل</b><span>ابدئي بطلبات تحتاج متابعة، ثم افتحي التفاصيل لتشاهدي الرسالة أو الروشتة وتغيري حالة الطلب.</span></div><button class="ghost-btn" data-action="go-pending">عرض الطلبات الجديدة</button></section><div class="stat-grid">${stat('تحتاج متابعة', followUp.length, 'fa-bell', 'attention')}${stat('مواعيد اليوم', day.length, 'fa-calendar-day')}${stat('مواعيد مؤكدة', confirmed.length, 'fa-circle-check', 'good')}${stat('تمت الزيارة', completed.length, 'fa-heart-circle-check')}${stat('طلبات بها مرفق', appointments.filter(hasAttachment).length, 'fa-paperclip')}</div><section class="panel urgent-panel"><div class="panel-title"><div><h2>طلبات تحتاج متابعة</h2><p>طلبات جديدة أو تم تأجيلها — اضغطي على أي طلب لفتح بيانات المريضة كاملة.</p></div><span class="count-badge">${followUp.length}</span></div><div class="appointment-grid">${followUp.length ? followUp.slice(0, 12).map(requestCard).join('') : emptyState('fa-circle-check', 'لا توجد طلبات تحتاج متابعة الآن.')}</div></section><section class="panel"><div class="panel-title"><div><h2>مواعيد ${formatDate(selectedDate)}</h2><p>اختاري يومًا آخر لمراجعة جدول المواعيد.</p></div><input type="date" id="dayPicker" value="${selectedDate}"></div><div class="appointment-grid compact">${day.length ? day.map(requestCard).join('') : emptyState('fa-calendar-xmark', 'لا توجد مواعيد مسجلة لهذا اليوم.')}</div></section>`;
}
function requestCard(a) {
  const phone = safePhone(a.patients?.phone); const attachment = hasAttachment(a) ? `<span class="attachment-badge"><i class="fa-solid fa-paperclip"></i> مرفق</span>` : '';
  return `<article class="request-card status-${a.status}"><div class="request-card-top"><span class="status ${escapeHtml(a.status)}"><i class="fa-solid ${statusIcons[a.status] || 'fa-circle'}"></i> ${statusLabels[a.status] || 'طلب جديد'}</span>${attachment}</div><button class="request-main" data-action="details" data-id="${Number(a.id)}"><b>${escapeHtml(a.patients?.full_name || 'مريضة غير مسجلة')}</b><span><i class="fa-solid fa-stethoscope"></i> ${escapeHtml(typeText(a.request_type))}</span><span><i class="fa-solid fa-calendar"></i> ${escapeHtml(requestDate(a))}</span>${a.message ? `<small>“${escapeHtml(a.message)}”</small>` : '<small class="muted">لا توجد رسالة إضافية</small>'}</button><div class="request-actions"><a href="tel:${phone}" class="icon-action call" title="اتصال"><i class="fa-solid fa-phone"></i><span>اتصال</span></a><a href="${wa(a)}" target="_blank" rel="noopener" class="icon-action whatsapp" title="واتساب"><i class="fa-brands fa-whatsapp"></i><span>واتساب</span></a><button class="icon-action details" data-action="details" data-id="${Number(a.id)}"><i class="fa-solid fa-arrow-left"></i><span>التفاصيل</span></button></div></article>`;
}
function emptyState(icon, message) { return `<div class="empty"><i class="fa-solid ${icon}"></i><span>${message}</span></div>`; }
function appointmentsView() { return `<section class="panel"><div class="panel-title"><div><h2>كل الطلبات</h2><p>ابحثي بالاسم أو رقم الهاتف، أو حددي الحالة والتاريخ.</p></div><button class="ghost-btn" data-action="clear-filters">مسح التصفية</button></div><div class="toolbar"><input id="searchAppointments" placeholder="بحث بالاسم أو الهاتف"><select id="statusFilter"><option value="">كل الحالات</option>${Object.entries(statusLabels).map(([key,label]) => `<option value="${key}">${label}</option>`).join('')}</select><input type="date" id="filterDate" value=""></div><div id="appointmentsList" class="appointment-grid all-requests">${appointments.length ? appointments.map(requestCard).join('') : emptyState('fa-calendar-xmark', 'لا توجد طلبات مسجلة بعد.')}</div></section>`; }
function patientsView() { const patients = Object.values(appointments.reduce((all, appointment) => { if (appointment.patients) all[appointment.patients.id] = appointment.patients; return all; }, {})); return `<section class="panel"><div class="panel-title"><div><h2>ملفات المريضات</h2><p>اختاري ملف المريضة لرؤية كل زياراتها وطلباتِها السابقة.</p></div><input id="searchPatients" placeholder="بحث بالاسم أو الهاتف"></div><div id="patientsList" class="patients-list">${patients.length ? patients.map(patientCard).join('') : emptyState('fa-users', 'لا توجد مريضات مسجلات بعد.')}</div></section>`; }
function patientCard(patient) { const visits = appointments.filter(a => a.patient_id === patient.id); return `<button class="patient-card" data-action="patient" data-patient="${escapeHtml(patient.id)}"><span class="patient-avatar">${escapeHtml(patient.full_name?.trim().charAt(0) || 'م')}</span><span><b>${escapeHtml(patient.full_name)}</b><small>${escapeHtml(safePhone(patient.phone))} · ${visits.length} طلب</small></span><i class="fa-solid fa-arrow-left"></i></button>`; }
function reportsView() { const month = appointments.filter(a => a.created_at?.slice(0, 7) === new Date().toISOString().slice(0, 7)); const completed = month.filter(a => a.status === 'completed').length; const rate = month.length ? Math.round(completed / month.length * 100) : 0; const types = {}; month.forEach(a => { const name = typeText(a.request_type); types[name] = (types[name] || 0) + 1; }); return `<div class="stat-grid report-stats">${stat('طلبات هذا الشهر', month.length, 'fa-calendar')}${stat('تمت الزيارة', completed, 'fa-heart-circle-check', 'good')}${stat('نسبة الحضور', `${rate}%`, 'fa-chart-line')}${stat('إلغاءات', month.filter(a => a.status === 'cancelled').length, 'fa-ban')}${stat('مرفقات', month.filter(hasAttachment).length, 'fa-paperclip')}</div><section class="panel"><h2>الطلبات حسب الخدمة</h2><div class="report-grid">${Object.entries(types).map(([name,count]) => `<div class="report-item"><span>${escapeHtml(name)}</span><b>${count}</b></div>`).join('') || emptyState('fa-chart-pie', 'لا توجد بيانات لهذا الشهر.')}</div></section>`; }
function settingsView() { if (!settings) return `<section class="panel">${emptyState('fa-triangle-exclamation', 'تعذر تحميل الإعدادات.')}</section>`; return `<section class="panel"><div class="panel-title"><div><h2>تشغيل العيادة</h2><p>هذه الإعدادات تظهر للدكتورة فقط.</p></div><span class="status confirmed">للدكتورة فقط</span></div><form id="settingsForm" class="settings-grid"><label class="field">اسم العيادة<input name="clinic_name" value="${escapeHtml(settings.clinic_name)}"></label><label class="field">الحد الأقصى للحجوزات يوميًا<input name="max_daily_slots" type="number" min="1" value="${Number(settings.max_daily_slots) || 1}"></label><label class="field">بداية العمل<input name="work_start" type="time" value="${escapeHtml(settings.work_start)}"></label><label class="field">نهاية العمل<input name="work_end" type="time" value="${escapeHtml(settings.work_end)}"></label><label class="field">تواريخ الإجازات (كل تاريخ في سطر)<textarea name="closed_dates">${escapeHtml((settings.closed_dates || []).join('\n'))}</textarea></label><label class="field">أيام الإجازة الأسبوعية<select name="closed_weekdays" multiple><option value="4" ${(settings.closed_weekdays || []).includes(4) ? 'selected' : ''}>الخميس</option><option value="5" ${(settings.closed_weekdays || []).includes(5) ? 'selected' : ''}>الجمعة</option><option value="6" ${(settings.closed_weekdays || []).includes(6) ? 'selected' : ''}>السبت</option></select></label><button class="primary-btn" type="submit">حفظ الإعدادات</button></form></section>`; }

function detailsModal(a) {
  if (!a) return ''; const events = (a.appointment_events || []).sort((x,y) => new Date(y.created_at) - new Date(x.created_at)); const attachment = attachmentData(a); const isImage = safeAttachmentType(a.attachment_type).startsWith('image/');
  const attachmentHtml = attachment ? `<section class="attachment-view"><div class="attachment-title"><b><i class="fa-solid fa-paperclip"></i> مرفق المريضة</b><small>${escapeHtml(a.attachment_name || 'ملف مرفق')}</small><a href="${attachment}" target="_blank" rel="noopener" class="ghost-btn">فتح بحجم كامل</a></div>${isImage ? `<img src="${attachment}" alt="مرفق المريضة">` : `<iframe src="${attachment}" title="مرفق المريضة"></iframe>`}</section>` : `<div class="no-attachment"><i class="fa-solid fa-paperclip"></i> لم تُرفق المريضة روشتة أو تحليلًا.</div>`;
  return `<div class="modal" id="modal"><section class="modal-card"><div class="modal-head"><div><h2>بيانات طلب الحجز</h2><p>${escapeHtml(a.booking_code || 'طلب من الموقع')} · سُجل ${new Date(a.created_at).toLocaleString('ar-EG')}</p></div><button class="ghost-btn" data-action="close-modal">إغلاق</button></div><div class="patient-data"><div class="data-box"><span>اسم المريضة</span><b>${escapeHtml(a.patients?.full_name || '-')}</b></div><div class="data-box"><span>رقم الهاتف</span><b dir="ltr">${escapeHtml(safePhone(a.patients?.phone))}</b></div><div class="data-box"><span>نوع الطلب</span><b>${escapeHtml(typeText(a.request_type))}</b></div><div class="data-box"><span>الموعد المطلوب</span><b>${escapeHtml(requestDate(a))}</b></div>${a.last_visit_date ? `<div class="data-box"><span>آخر زيارة</span><b>${formatDate(a.last_visit_date)}</b></div>` : ''}</div><div class="contact-actions"><a href="tel:${safePhone(a.patients?.phone)}" class="primary-btn"><i class="fa-solid fa-phone"></i> اتصال بالمريضة</a><a href="${wa(a)}" target="_blank" rel="noopener" class="whatsapp-btn"><i class="fa-brands fa-whatsapp"></i> واتساب</a></div>${a.message ? `<section class="message-box"><b><i class="fa-solid fa-message"></i> رسالة المريضة</b><p>${escapeHtml(a.message)}</p></section>` : ''}${attachmentHtml}<section class="update-box"><h3>تحديث حالة الطلب</h3><div class="status-steps">${Object.entries(statusLabels).map(([key,label]) => `<button class="status-choice ${a.status === key ? 'selected' : ''}" data-action="quick-status" data-id="${Number(a.id)}" data-status="${key}"><i class="fa-solid ${statusIcons[key]}"></i>${label}</button>`).join('')}</div><label class="field">ملاحظة داخلية للعيادة<textarea id="staffNote" placeholder="مثال: تم التواصل وحددنا الساعة 6 مساءً">${escapeHtml(a.staff_note || '')}</textarea></label><button class="primary-btn" data-action="save-appointment" data-id="${Number(a.id)}">حفظ التحديث</button></section><section class="history"><h3>سجل الطلب</h3>${events.length ? events.map(event => `<div class="event"><b>${event.event_type === 'created' ? 'تم استلام الطلب' : 'تم التحديث'}</b><span>${escapeHtml(event.note || '')}</span><small>${new Date(event.created_at).toLocaleString('ar-EG')}</small></div>`).join('') : '<p class="muted">لا يوجد سجل بعد.</p>'}</section></section></div>`;
}
function patientModal(id) { const patient = appointments.find(a => a.patient_id === id)?.patients; if (!patient) return ''; const visits = appointments.filter(a => a.patient_id === id); return `<div class="modal" id="modal"><section class="modal-card"><div class="modal-head"><div><h2>ملف المريضة</h2><p>كل الطلبات المسجلة باسمها</p></div><button class="ghost-btn" data-action="close-modal">إغلاق</button></div><div class="patient-profile"><span class="patient-avatar">${escapeHtml(patient.full_name?.trim().charAt(0) || 'م')}</span><div><b>${escapeHtml(patient.full_name)}</b><small dir="ltr">${escapeHtml(safePhone(patient.phone))}</small></div><a href="tel:${safePhone(patient.phone)}" class="icon-action call"><i class="fa-solid fa-phone"></i> اتصال</a></div><div class="appointment-grid compact">${visits.map(requestCard).join('')}</div></section></div>`; }

function bindEvents() {
  app.onclick = async event => { const target = event.target.closest('[data-action],[data-view]'); if (!target) return;
    if (target.dataset.view) { activeView = target.dataset.view; return renderApp(); }
    if (target.dataset.action === 'logout') { await supabase.auth.signOut(); session = null; return renderLogin(); }
    if (target.dataset.action === 'details') { app.insertAdjacentHTML('beforeend', detailsModal(appointmentById(target.dataset.id))); return; }
    if (target.dataset.action === 'patient') { app.insertAdjacentHTML('beforeend', patientModal(target.dataset.patient)); return; }
    if (target.dataset.action === 'close-modal') { document.getElementById('modal')?.remove(); return; }
    if (target.dataset.action === 'go-pending') { activeView = 'appointments'; renderApp(); document.getElementById('statusFilter').value = 'new'; filterAppointments(); return; }
    if (target.dataset.action === 'clear-filters') { document.getElementById('searchAppointments').value = ''; document.getElementById('statusFilter').value = ''; document.getElementById('filterDate').value = ''; filterAppointments(); return; }
    if (target.dataset.action === 'quick-status') { const modal = document.getElementById('modal'); modal.querySelectorAll('.status-choice').forEach(button => button.classList.toggle('selected', button === target)); modal.dataset.pendingStatus = target.dataset.status; return; }
    if (target.dataset.action === 'save-appointment') await saveAppointment(Number(target.dataset.id));
  };
  app.oninput = event => { if (event.target.id === 'searchAppointments') filterAppointments(); if (event.target.id === 'searchPatients') filterPatients(event.target.value); };
  app.onchange = event => { if (event.target.id === 'dayPicker') { selectedDate = event.target.value; renderView(); } if (event.target.id === 'statusFilter' || event.target.id === 'filterDate') filterAppointments(); };
  document.getElementById('settingsForm')?.addEventListener('submit', saveSettings);
}
function filterAppointments() { const query = document.getElementById('searchAppointments')?.value.trim() || ''; const status = document.getElementById('statusFilter')?.value || ''; const date = document.getElementById('filterDate')?.value || ''; const matches = appointments.filter(a => (!query || `${a.patients?.full_name || ''}${a.patients?.phone || ''}${a.booking_code || ''}`.includes(query)) && (!status || a.status === status) && (!date || a.requested_date === date)); document.getElementById('appointmentsList').innerHTML = matches.length ? matches.map(requestCard).join('') : emptyState('fa-magnifying-glass', 'لا توجد طلبات مطابقة للبحث.'); }
function filterPatients(query) { const people = Object.values(appointments.reduce((all,a) => { if (a.patients) all[a.patients.id] = a.patients; return all; }, {})).filter(p => `${p.full_name}${p.phone}`.includes(query)); document.getElementById('patientsList').innerHTML = people.length ? people.map(patientCard).join('') : emptyState('fa-magnifying-glass', 'لا توجد مريضة مطابقة للبحث.'); }
async function saveAppointment(id) { const appointment = appointmentById(id); const modal = document.getElementById('modal'); const status = modal.dataset.pendingStatus || appointment.status; const note = modal.querySelector('#staffNote').value.trim(); const { error } = await supabase.from('appointments').update({ status, staff_note:note }).eq('id', id); if (error) return showToast('تعذر حفظ التحديث. أعيدي المحاولة.'); const eventNote = note || `تم تغيير الحالة إلى ${statusLabels[status]}.`; const { error: eventError } = await supabase.from('appointment_events').insert({ appointment_id:id, actor_id:session.user.id, event_type:'updated', old_status:appointment.status, new_status:status, note:eventNote }); if (eventError) return showToast('تم حفظ الحالة، لكن تعذر حفظ ملاحظة السجل.'); await loadData(); modal.remove(); renderApp(); showToast('تم حفظ تحديث الطلب بنجاح.'); }
async function saveSettings(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const closed_weekdays = Array.from(event.currentTarget.closed_weekdays.selectedOptions).map(option => Number(option.value)); const closed_dates = String(form.get('closed_dates')).split(/\s+/).filter(Boolean); const { error } = await supabase.from('clinic_settings').update({ clinic_name:form.get('clinic_name'), max_daily_slots:Number(form.get('max_daily_slots')), work_start:form.get('work_start'), work_end:form.get('work_end'), closed_weekdays, closed_dates }).eq('id', true); if (error) return showToast('تعذر حفظ الإعدادات.'); await loadData(); showToast('تم حفظ الإعدادات بنجاح.'); }
function showToast(message) { const toast = document.getElementById('toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3200); }
